version: '3'

services:
    frontend:
        image: frontend
        ports:
            - 5000:5000
        container_name: frontend
        depends_on:
            - backend
 
    backend:
        image: backend
        ports:
            - 8080:8080
        container_name: backend
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - redis
            - postgres
 
    redis:
        image: redis
        restart: unless-stopped
        container_name: redis

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./database:/var/lib/postgresql/data
        restart: unless-stopped
        container_name: postgres

    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        container_name: nginx
        restart: unless-stopped
        depends_on:
            - frontend